list.files("/anvil/projects/tdm/data/craigslist")
myDF <- read.csv("/anvil/projects/tdm/data/craigslist/vehicles.csv", stringsAsFactors = TRUE)
options(repr.matrix.max.cols=25, repr.matrix.max.rows=200)
options(jupyter.rich_display = F)
head(myDF)
head(myDF$region)
head(table(myDF$region),n = 5)
length(table(myDF$region))
car_year <- (myDF$year)
newer <- rep("Older than 2011", times = length(car_year))
newer[car_year > 2010] <- "Newer than or recent as 2011"
table(newer)
year_in_order <- myDF$year[order(myDF$year)]
year_in_order <- na.omit(year_in_order)
head(year_in_order)
tail(year_in_order)
tail(sort(table(year_in_order)))
head(myDF$condition)
table(myDF$condition, useNA= "always")
myDF$newflag <- NA
myDF$newflag[myDF$condition == "like new"] <- TRUE
myDF$newflag[myDF$condition != "like new"] <- FALSE
table(myDF$newflag)
head(myDF[,c("newflag","condition")], n = 10)
head(myDF$price)
myDF$pricecategory <- NA
myDF$pricecategory[myDF$price <= 1500] <- "cheap"
myDF$pricecategory[(myDF$price > 1500) & (myDF$price <= 10000)] <- "average"
myDF$pricecategory[myDF$price > 10000] <- "expensive"
head(myDF[,c("price", "pricecategory")], n = 10)
sort(table(myDF$pricecategory))
table(myDF$newflag)
myDF$newpricecategory <- cut(myDF$price, breaks = c(-Inf, 1500, 10000, Inf), labels = c("cheap", "average", "expensive"))
head(myDF$newpricecategory)
table(myDF$newpricecategory, useNA = "always")
head(myDF[,c("pricecategory","newpricecategory")])
sum(myDF$pricecategory == myDF$newpricecategory)
dim(myDF)
myDF$odometerage <- cut(myDF$odometer, breaks = c(-Inf, 50000, 100000, Inf), labels = c("new", "middle age", "old"))
head(myDF[,c("odometerage","odometer")])
table(myDF$odometerage, useNA = "always")
head(myDF$region)
myIndy <- subset(myDF, (region =="indianapolis") & (!is.na(long)) & (!is.na(lat)))
dim(myIndy)
tail(sort(table(myDF$region)))
popularRegion <- subset(myDF, (region == "springfield")  & (!is.na(long)) & (!is.na(lat)))
dim(popularRegion)
myNYC <- subset(myDF, (region == "new york city")  & (!is.na(long)) & (!is.na(lat)))
dim(myNYC)
library(leaflet)
library(sf)
options(jupyter.rich_display = T)
points <- st_as_sf(myIndy, coords = c("long", "lat"), crs = 4326)
addCircleMarkers(addTiles(leaflet(myIndy)), radius = 1)
points <- st_as_sf(popularRegion, coords = c("long", "lat"), crs = 4326)
addCircleMarkers(addTiles(leaflet(popularRegion)), radius = 1)
points <- st_as_sf(myNYC, coords = c("long", "lat"), crs = 4326)
addCircleMarkers(addTiles(leaflet(myNYC)), radius = 1)
